# Tree-based Classifier

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [2]:
df = pd.read_csv("Arrests_cleaned_with_location.csv")
df = df.dropna(subset=["Latitude", "Longitude"])
df

,ACB_NO,CASE NUMBER,ARREST MONTH,ARREST DATE,ARREST YEAR,ARREST TIME,ARREST MERIDIEM,RACE,CHARGE 1 STATUTE,CHARGE 1 DESCRIPTION,...,CHARGE 4 STATUTE,CHARGE 4 DESCRIPTION,CHARGE 4 TYPE,CHARGE 4 CLASS,CHARGES STATUTE,CHARGES DESCRIPTION,CHARGES TYPE,CHARGES CLASS,Latitude,Longitude
2,18908465,HX290868,6,5,2014,11:58:00,AM,BLACK,720 ILCS 570.0/402-C,PCS - POSSESSION - POSS AMT CON SUB EXCEPT (A)(D),...,NaN,NaN,NaN,NaN,720 ILCS 570.0/402-C | 720 ILCS 600.0/3.5-A | |,PCS - POSSESSION - POSS AMT CON SUB EXCEPT (A)...,F | M | |,4 | A | |,41.877464,-87.763012
3,18914257,HX302763,6,14,2014,4:50:00,AM,BLACK,720 ILCS 5.0/12-3-A-1,BATTERY - CAUSE BODILY HARM,...,NaN,NaN,NaN,NaN,720 ILCS 5.0/12-3-A-1 | 520 ILCS 5.0/1.22 | 72...,BATTERY - CAUSE BODILY HARM | RESIST/OBSTRUCT ...,M | M | M |,A | A | A |,41.885393,-87.663548
5,18921756,HX318527,6,25,2014,4:35:00,PM,BLACK,720 ILCS 5.0/19-4-A-1,CRIM TRESPASS TO RESIDENCE,...,NaN,NaN,NaN,NaN,720 ILCS 5.0/19-4-A-1 | | |,CRIM TRESPASS TO RESIDENCE | | |,M | | |,A | | |,41.750435,-87.657916
6,18911533,HX297219,6,10,2014,12:15:00,AM,WHITE HISPANIC,720 ILCS 5.0/12-3.2-A-2,DOMESTIC BATTERY - PHYSICAL CONTACT,...,NaN,NaN,NaN,NaN,720 ILCS 5.0/12-3.2-A-2 | 720 ILCS 5.0/12-3.5-...,DOMESTIC BATTERY - PHYSICAL CONTACT | INTERF R...,M | M | |,A | A | |,41.935168,-87.747779
7,18919006,HX312887,6,21,2014,12:30:00,PM,BLACK,10-8-515,SOLICITING UNLAWFUL BUSINESS,...,NaN,NaN,NaN,NaN,10-8-515 | | |,SOLICITING UNLAWFUL BUSINESS | | |,| | |,L | | |,41.896812,-87.748911
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
569735,30178472,JF400508,9,18,2022,7:10:00,AM,BLACK,720 ILCS 5.0/21-3-A-1,CRIMINAL TRESPASS TO REAL PROPERTY,...,NaN,NaN,NaN,NaN,720 ILCS 5.0/21-3-A-1 | | |,CRIMINAL TRESPASS TO REAL PROPERTY | | |,M | | |,B | | |,0.000000,0.000000
570001,19263360,HZ148289,2,11,2016,5:38:00,PM,BLACK,720 ILCS 5.0/12-3-A-2,BATTERY - MAKE PHYSICAL CONTACT,...,NaN,NaN,NaN,NaN,720 ILCS 5.0/12-3-A-2 | 720 ILCS 5.0/16-25-A-1...,BATTERY - MAKE PHYSICAL CONTACT | RETAIL THEFT...,M | M | |,A | A | |,41.728227,-87.552855
570268,19028723,HX541848,12,14,2014,10:58:00,AM,BLACK,720 ILCS 5.0/24-1.1-A,UUW - WEAPON - FELON POSSES WEAPON/2ND+,...,625 ILCS 5.0/6-303-A,DRIVING ON SUSPENDED LICENSE,M,A,720 ILCS 5.0/24-1.1-A | 720 ILCS 5.0/24-1.1-A ...,UUW - WEAPON - FELON POSSES WEAPON/2ND+ | UUW ...,F | F | M | M,2 | 2 | A | A,41.879366,-87.755845
570673,18956377,HX389427,8,15,2014,10:55:00,PM,BLACK,720 ILCS 570.0/402-C,PCS - POSSESSION - POSS AMT CON SUB EXCEPT (A)(D),...,NaN,NaN,NaN,NaN,720 ILCS 570.0/402-C | 720 ILCS 550.0/4-D | |,PCS - POSSESSION - POSS AMT CON SUB EXCEPT (A)...,F | F | |,4 | 4 | |,41.762780,-87.651629
570885,30182978,HY373142,10,4,2022,8:30:00,PM,WHITE HISPANIC,720 ILCS 5.0/11-1.40-A-1,PRED CRIM SEX ASLT/VICTIM <13,...,NaN,NaN,NaN,NaN,720 ILCS 5.0/11-1.40-A-1 | | |,PRED CRIM SEX ASLT/VICTIM <13 | | |,F | | |,X | | |,41.847555,-87.711219

In [3]:
print("size of the dataset: ", len(df))
df.columns

size of the dataset:  102103

Index(['ACB_NO', 'CASE NUMBER', 'ARREST MONTH', 'ARREST DATE', 'ARREST YEAR',
       'ARREST TIME', 'ARREST MERIDIEM', 'RACE', 'CHARGE 1 STATUTE',
       'CHARGE 1 DESCRIPTION', 'CHARGE 1 TYPE', 'CHARGE 1 CLASS',
       'CHARGE 2 STATUTE', 'CHARGE 2 DESCRIPTION', 'CHARGE 2 TYPE',
       'CHARGE 2 CLASS', 'CHARGE 3 STATUTE', 'CHARGE 3 DESCRIPTION',
       'CHARGE 3 TYPE', 'CHARGE 3 CLASS', 'CHARGE 4 STATUTE',
       'CHARGE 4 DESCRIPTION', 'CHARGE 4 TYPE', 'CHARGE 4 CLASS',
       'CHARGES STATUTE', 'CHARGES DESCRIPTION', 'CHARGES TYPE',
       'CHARGES CLASS', 'Latitude', 'Longitude'],
      dtype='object')

## Data Preprocessing

In [4]:
races = df.loc[:, "RACE"].unique()
c1_types = df.loc[:, "CHARGE 1 TYPE"].unique()
print("races: ", races)
print("charge 1 type: ", c1_types)

races:  ['BLACK' 'WHITE HISPANIC' 'WHITE' 'BLACK HISPANIC'
 'ASIAN / PACIFIC ISLANDER' 'UNKNOWN / REFUSED'
 'AMER INDIAN / ALASKAN NATIVE']
charge 1 type:  ['F' 'M' 'O' 'A' 'R']

In [5]:
race_dummies = pd.get_dummies(df, columns=["RACE"])
dummy_races = ['RACE_AMER INDIAN / ALASKAN NATIVE', \
               'RACE_ASIAN / PACIFIC ISLANDER', 'RACE_BLACK', 'RACE_BLACK HISPANIC', \
               'RACE_UNKNOWN / REFUSED', 'RACE_WHITE', 'RACE_WHITE HISPANIC']
race_dummies = race_dummies[dummy_races]
race_dummies

,RACE_AMER INDIAN / ALASKAN NATIVE,RACE_ASIAN / PACIFIC ISLANDER,RACE_BLACK,RACE_BLACK HISPANIC,RACE_UNKNOWN / REFUSED,RACE_WHITE,RACE_WHITE HISPANIC
2,0,0,1,0,0,0,0
3,0,0,1,0,0,0,0
5,0,0,1,0,0,0,0
6,0,0,0,0,0,0,1
7,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...
569735,0,0,1,0,0,0,0
570001,0,0,1,0,0,0,0
570268,0,0,1,0,0,0,0
570673,0,0,1,0,0,0,0
570885,0,0,0,0,0,0,1

In [6]:
month_dummies = pd.get_dummies(df, columns=["ARREST MONTH"])
dummy_month = ['ARREST MONTH_1', 'ARREST MONTH_2', 'ARREST MONTH_3', 'ARREST MONTH_4', \
       'ARREST MONTH_5', 'ARREST MONTH_6', 'ARREST MONTH_7', 'ARREST MONTH_8', \
       'ARREST MONTH_9', 'ARREST MONTH_10', 'ARREST MONTH_11', 'ARREST MONTH_12']
month_dummies = month_dummies[dummy_month]
month_dummies

,ARREST MONTH_1,ARREST MONTH_2,ARREST MONTH_3,ARREST MONTH_4,ARREST MONTH_5,ARREST MONTH_6,ARREST MONTH_7,ARREST MONTH_8,ARREST MONTH_9,ARREST MONTH_10,ARREST MONTH_11,ARREST MONTH_12
2,0,0,0,0,0,1,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,0,0
5,0,0,0,0,0,1,0,0,0,0,0,0
6,0,0,0,0,0,1,0,0,0,0,0,0
7,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
569735,0,0,0,0,0,0,0,0,1,0,0,0
570001,0,1,0,0,0,0,0,0,0,0,0,0
570268,0,0,0,0,0,0,0,0,0,0,0,1
570673,0,0,0,0,0,0,0,1,0,0,0,0
570885,0,0,0,0,0,0,0,0,0,1,0,0

In [7]:
arrest_case_num = df.loc[:, "CASE NUMBER"].str[2:].astype(int)
arrest_case_num

2         290868
3         302763
5         318527
6         297219
7         312887
           ...
569735    400508
570001    148289
570268    541848
570673    389427
570885    373142
Name: CASE NUMBER, Length: 102103, dtype: int32

In [8]:
arrest_ampm = df.loc[:, "ARREST MERIDIEM"].apply(lambda x: 1 if x == "AM" else 0)
arrest_ampm

2         1
3         1
5         0
6         1
7         0
         ..
569735    1
570001    0
570268    1
570673    0
570885    0
Name: ARREST MERIDIEM, Length: 102103, dtype: int64

In [9]:
arrest_time = df.loc[:, "ARREST TIME"].str.split(":").apply(lambda x: x[0]).astype(int)
arrest_time

2         11
3          4
5          4
6         12
7         12
          ..
569735     7
570001     5
570268    10
570673    10
570885     8
Name: ARREST TIME, Length: 102103, dtype: int32

In [10]:
arrest_date = df.loc[:, "ARREST DATE"].astype(int)
arrest_date

2          5
3         14
5         25
6         10
7         21
          ..
569735    18
570001    11
570268    14
570673    15
570885     4
Name: ARREST DATE, Length: 102103, dtype: int32

In [11]:
arrest_long = df.loc[:, "Longitude"]
arrest_long

2        -87.763012
3        -87.663548
5        -87.657916
6        -87.747779
7        -87.748911
            ...
569735     0.000000
570001   -87.552855
570268   -87.755845
570673   -87.651629
570885   -87.711219
Name: Longitude, Length: 102103, dtype: float64

In [12]:
arrest_lat = df.loc[:, "Latitude"]
arrest_lat

2         41.877464
3         41.885393
5         41.750435
6         41.935168
7         41.896812
            ...
569735     0.000000
570001    41.728227
570268    41.879366
570673    41.762780
570885    41.847555
Name: Latitude, Length: 102103, dtype: float64

### Binary Charge Types: Serious (Misdemeanor & Felony) vs Non-Serious

In [13]:
# binary charge types
# serious crime ('M' 'F' 'A' 'R' 'V') labelled as 1, 'O' labelled as 0
charge_types = df.loc[:, "CHARGE 1 TYPE"].apply(lambda x: 0 if x == "O" else 1)
charge_types.value_counts()

1    97435
0     4668
Name: CHARGE 1 TYPE, dtype: int64

### Multi-Class Charge Types: Misdemeanor, Felony & Others

In [14]:
# three charge types
m_charge_types = df.loc[:, "CHARGE 1 TYPE"].replace('A', 'M')
m_charge_types = m_charge_types.replace('R', 'O')
m_charge_types = m_charge_types.replace('V', 'O')
multi_class_types = pd.factorize(m_charge_types)
multi_class_types = multi_class_types[0]
m_charge_types.value_counts()

M    62857
F    34577
O     4669
Name: CHARGE 1 TYPE, dtype: int64

In [15]:
data = pd.concat([arrest_case_num, arrest_ampm, arrest_time, arrest_long, arrest_lat, month_dummies, race_dummies], axis=1)
data

,CASE NUMBER,ARREST MERIDIEM,ARREST TIME,Longitude,Latitude,ARREST MONTH_1,ARREST MONTH_2,ARREST MONTH_3,ARREST MONTH_4,ARREST MONTH_5,...,ARREST MONTH_10,ARREST MONTH_11,ARREST MONTH_12,RACE_AMER INDIAN / ALASKAN NATIVE,RACE_ASIAN / PACIFIC ISLANDER,RACE_BLACK,RACE_BLACK HISPANIC,RACE_UNKNOWN / REFUSED,RACE_WHITE,RACE_WHITE HISPANIC
2,290868,1,11,-87.763012,41.877464,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,302763,1,4,-87.663548,41.885393,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
5,318527,0,4,-87.657916,41.750435,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
6,297219,1,12,-87.747779,41.935168,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7,312887,0,12,-87.748911,41.896812,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
569735,400508,1,7,0.000000,0.000000,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
570001,148289,0,5,-87.552855,41.728227,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
570268,541848,1,10,-87.755845,41.879366,0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
570673,389427,0,10,-87.651629,41.762780,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
570885,373142,0,8,-87.711219,41.847555,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1

### Train Testing Split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(data, charge_types, test_size = 0.2)
print("train-test-sizes: ", len(X_train), len(X_test))

train-test-sizes:  81682 20421

In [17]:
X_train, X_test, y_train_m, y_test_m = train_test_split(data, multi_class_types, test_size = 0.2)
print("train-test-sizes: ", len(X_train), len(X_test))

train-test-sizes:  81682 20421

## Random Forest

### Training (Binary Charge Types)

In [23]:
# creating a Random Forest classifier
clf = RandomForestClassifier(n_estimators = 100)

# Training the model on the training dataset
# fit function is used to train the model using the training sets as parameters
clf.fit(X_train, y_train)

RandomForestClassifier()

### Testing (Binary Charge Types)

In [30]:
# performing predictions on the test dataset
y_pred = clf.predict(X_test)

# using metrics module for accuracy calculation
print("ACCURACY OF THE MODEL: ", metrics.accuracy_score(y_test, y_pred))

ACCURACY OF THE MODEL:  0.9503452328485382

### Training (Multi-Class Charge Types)

In [ ]:
# creating a Random Forest classifier
from sklearn.model_selection import cross_val_score
clf_m = RandomForestClassifier(n_estimators = 100)

# Training the model on the training dataset
# fit function is used to train the model using the training sets as parameters
clf_m.fit(X_train, y_train_m)
scores_RF = cross_val_score(clf_m, X_train,y_train_m, cv=5)

In [43]:
from sklearn.model_selection import GridSearchCV
#n_estimators max_depth min_samples_leaf min_samples_split max_features
parameters = {'max_depth':[i for i in range(1, 51,10)],'min_samples_leaf':[i for i in range(1, 12, 2)]}
clf_mCV = GridSearchCV(clf_m, parameters,cv=5)
clf_mCV.fit(X_train,y_train_m)
clf_mCV.cv_results_

{'mean_fit_time': array([0.73536868, 0.72661171, 0.72818704, 0.71681204, 0.72482548,
        0.73544278, 3.24283581, 3.20669999, 3.18962169, 3.15379243,
        3.13580351, 3.11399741, 5.38413119, 4.87039514, 4.66788259,
        4.55229554, 4.41991024, 4.30629368, 6.39316611, 5.84510183,
        5.78114991, 5.19410973, 4.97958846, 4.83992343, 7.06497769,
        5.84263253, 5.36741748, 5.37681274, 4.98144898, 4.80861902]),
 'std_fit_time': array([0.01144311, 0.00933147, 0.03843175, 0.02115598, 0.01702086,
        0.00791148, 0.03350886, 0.05466733, 0.04848273, 0.04429159,
        0.03094394, 0.01146958, 0.03323794, 0.05575332, 0.03226147,
        0.04115638, 0.07389371, 0.04273847, 0.06430462, 0.17384481,
        0.31651211, 0.01997192, 0.02518772, 0.05143507, 0.03402368,
        0.01791449, 0.04082437, 0.19641267, 0.07100209, 0.08361135]),
 'mean_score_time': array([0.0558732 , 0.06093531, 0.05599751, 0.05621777, 0.05573845,
        0.05703645, 0.15740118, 0.15501804, 0.1519486 , 0.1488699 ,
        0.14924407, 0.15345807, 0.29862394, 0.26455035, 0.24358425,
        0.23822093, 0.2291081 , 0.22243304, 0.39313135, 0.32871113,
        0.30321155, 0.27396069, 0.2630178 , 0.24739571, 0.43104124,
        0.33011546, 0.28912525, 0.29643049, 0.26886578, 0.25239654]),
 'std_score_time': array([0.00150063, 0.00575642, 0.00169365, 0.00218503, 0.00230365,
        0.00279872, 0.00710158, 0.00532293, 0.00473917, 0.00429503,
        0.00999133, 0.00634914, 0.00780159, 0.00507908, 0.00477564,
        0.00788625, 0.00389295, 0.00262858, 0.01024306, 0.01175667,
        0.01601808, 0.0050391 , 0.00553003, 0.0076728 , 0.0084199 ,
        0.00841798, 0.00696799, 0.0307997 , 0.01035057, 0.0114393 ]),
 'param_max_depth': masked_array(data=[1, 1, 1, 1, 1, 1, 11, 11, 11, 11, 11, 11, 21, 21, 21,
                    21, 21, 21, 31, 31, 31, 31, 31, 31, 41, 41, 41, 41, 41,
                    41],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_leaf': masked_array(data=[1, 3, 5, 7, 9, 11, 1, 3, 5, 7, 9, 11, 1, 3, 5, 7, 9,
                    11, 1, 3, 5, 7, 9, 11, 1, 3, 5, 7, 9, 11],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 1, 'min_samples_leaf': 1},
  {'max_depth': 1, 'min_samples_leaf': 3},
  {'max_depth': 1, 'min_samples_leaf': 5},
  {'max_depth': 1, 'min_samples_leaf': 7},
  {'max_depth': 1, 'min_samples_leaf': 9},
  {'max_depth': 1, 'min_samples_leaf': 11},
  {'max_depth': 11, 'min_samples_leaf': 1},
  {'max_depth': 11, 'min_samples_leaf': 3},
  {'max_depth': 11, 'min_samples_leaf': 5},
  {'max_depth': 11, 'min_samples_leaf': 7},
  {'max_depth': 11, 'min_samples_leaf': 9},
  {'max_depth': 11, 'min_samples_leaf': 11},
  {'max_depth': 21, 'min_samples_leaf': 1},
  {'max_depth': 21, 'min_samples_leaf': 3},
  {'max_depth': 21, 'min_samples_leaf': 5},
  {'max_depth': 21, 'min_samples_leaf': 7},
  {'max_depth': 21, 'min_samples_leaf': 9},
  {'max_depth': 21, 'min_samples_leaf': 11},
  {'max_depth': 31, 'min_samples_leaf': 1},
  {'max_depth': 31, 'min_samples_leaf': 3},
  {'max_depth': 31, 'min_samples_leaf': 5},
  {'max_depth': 31, 'min_samples_leaf': 7},
  {'max_depth': 31, 'min_samples_leaf': 9},
  {'max_depth': 31, 'min_samples_leaf': 11},
  {'max_depth': 41, 'min_samples_leaf': 1},
  {'max_depth': 41, 'min_samples_leaf': 3},
  {'max_depth': 41, 'min_samples_leaf': 5},
  {'max_depth': 41, 'min_samples_leaf': 7},
  {'max_depth': 41, 'min_samples_leaf': 9},
  {'max_depth': 41, 'min_samples_leaf': 11}],
 'split0_test_score': array([0.61486197, 0.61486197, 0.61486197, 0.61486197, 0.61486197,
        0.61486197, 0.6486503 , 0.64852788, 0.6480382 , 0.6480382 ,
        0.64901757, 0.64797698, 0.66621779, 0.6588725 , 0.65507743,
        0.65599559, 0.65526106, 0.65354716, 0.6617494 , 0.66395299,
        0.65746465, 0.65624044, 0.65630165, 0.65366958, 0.65881129,
        0.66413662, 0.65936218, 0.65568954, 0.65770949, 0.65734223]),
 'split1_test_score': array([0.61486197, 0.61486197, 0.61486197, 0.61486197, 0.61486197,
        0.61486197, 0.65097631, 0.65164963, 0.65005815, 0.65042541,
        0.64987452, 0.6497521 , 0.66780927, 0.66248393, 0.66034156,
        0.65862766, 0.65850523, 0.65758707, 0.66419783, 0.66364694,
        0.66334088, 0.6617494 , 0.66070882, 0.65905613, 0.66125972,
        0.66725837, 0.66315725, 0.66236151, 0.66034156, 0.65875008]),
 'split2_test_score': array([0.61483839, 0.61483839, 0.61483839, 0.61483839, 0.61483839,
        0.61483839, 0.6511998 , 0.65095495, 0.65009794, 0.65193438,
        0.65156709, 0.65175073, 0.6701763 , 0.66405485, 0.66013712,
        0.65958619, 0.65774976, 0.65585211, 0.66613614, 0.66748286,
        0.66203477, 0.66123898, 0.65726004, 0.65640304, 0.66405485,
        0.66815622, 0.66332027, 0.66001469, 0.65726004, 0.65726004]),
 'split3_test_score': array([0.61483839, 0.61483839, 0.61483839, 0.61483839, 0.61483839,
        0.61483839, 0.65071009, 0.65236288, 0.6511998 , 0.65022037,
        0.65175073, 0.65187316, 0.66772772, 0.66423849, 0.6617287 ,
        0.66044319, 0.65774976, 0.65848433, 0.65970862, 0.66833986,
        0.66264691, 0.66050441, 0.65811704, 0.66025955, 0.65658668,
        0.66423849, 0.66283056, 0.66154505, 0.66074927, 0.65799461]),
 'split4_test_score': array([0.61483839, 0.61483839, 0.61483839, 0.61483839, 0.61483839,
        0.61483839, 0.64832272, 0.64783301, 0.64783301, 0.64832272,
        0.64728208, 0.64734329, 0.66589128, 0.66374878, 0.65946376,
        0.65695397, 0.65677032, 0.65585211, 0.66093291, 0.66870715,
        0.6634427 , 0.6583619 , 0.65823947, 0.65738247, 0.6549951 ,
        0.66717679, 0.66374878, 0.66062684, 0.65560725, 0.65744368]),
 'mean_test_score': array([0.61484782, 0.61484782, 0.61484782, 0.61484782, 0.61484782,
        0.61484782, 0.64997185, 0.65026567, 0.64944542, 0.64978822,
        0.6498984 , 0.64973925, 0.66756447, 0.66267971, 0.65934971,
        0.65832132, 0.65720723, 0.65626456, 0.66254498, 0.66642596,
        0.66178598, 0.65961903, 0.6581254 , 0.65735415, 0.65914153,
        0.6661933 , 0.66248381, 0.66004753, 0.65833352, 0.65775813]),
 'std_test_score': array([1.15498489e-05, 1.15498489e-05, 1.15498489e-05, 1.15498489e-05,
        1.15498489e-05, 1.15498489e-05, 1.22702214e-03, 1.77349895e-03,
        1.30071099e-03, 1.44284682e-03, 1.66356598e-03, 1.86794117e-03,
        1.51798071e-03, 1.99984494e-03, 2.25958956e-03, 1.64162992e-03,
        1.11820664e-03, 1.69710917e-03, 2.31969914e-03, 2.18277076e-03,
        2.21988492e-03, 2.04655319e-03, 1.46711072e-03, 2.27242276e-03,
        3.23903044e-03, 1.67367104e-03, 1.58859157e-03, 2.32059662e-03,
        1.94125549e-03, 5.58538655e-04]),
 'rank_test_score': array([25, 25, 25, 25, 25, 25, 20, 19, 24, 22, 21, 23,  1,  4, 10, 13, 17,
        18,  5,  2,  7,  9, 14, 16, 11,  3,  6,  8, 12, 15])}

In [45]:
clf_m = RandomForestClassifier(n_estimators = 100,max_depth=21,min_samples_leaf=1)
parameters = {'max_features':[i for i in range(14, 18)],'min_samples_split':[i for i in range(1, 5)]}
clf_mCV = GridSearchCV(clf_m, parameters,cv=5)
clf_mCV.fit(X_train,y_train_m)
clf_mCV.cv_results_

C:\Users\drizz\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
20 fits failed out of a total of 80.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\drizz\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\drizz\Anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 450, in fit
    trees = Parallel(
  File "C:\Users\drizz\Anaconda3\lib\site-packages\joblib\parallel.py", line 1043, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\drizz\Anaconda3\lib\site-packages\joblib\parallel.py", line 861, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\drizz\Anaconda3\lib\site-packages\joblib\parallel.py", line 779, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\drizz\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\drizz\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "C:\Users\drizz\Anaconda3\lib\site-packages\joblib\parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\drizz\Anaconda3\lib\site-packages\joblib\parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\drizz\Anaconda3\lib\site-packages\sklearn\utils\fixes.py", line 216, in __call__
    return self.function(*args, **kwargs)
  File "C:\Users\drizz\Anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 185, in _parallel_build_trees
    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
  File "C:\Users\drizz\Anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 937, in fit
    super().fit(
  File "C:\Users\drizz\Anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 250, in fit
    raise ValueError(
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\drizz\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:969: UserWarning: One or more of the test scores are non-finite: [       nan 0.67652607 0.67642813 0.67610983        nan 0.67645264
 0.6769913  0.67707701        nan 0.67699131 0.67673419 0.67623229
        nan 0.67593844 0.67641591 0.6761833 ]
  warnings.warn(

{'mean_fit_time': array([ 0.04832172, 15.09488578, 14.97632804, 14.90445666,  0.04332762,
        16.0275466 , 16.03549476, 15.90039377,  0.04453821, 17.00697846,
        16.86364541, 16.82666965,  0.04361253, 17.9415545 , 17.86023903,
        17.82978311]),
 'std_fit_time': array([0.00473723, 0.09906703, 0.07289215, 0.07994595, 0.00090685,
        0.07356101, 0.18251906, 0.06329653, 0.00124248, 0.04721995,
        0.0867579 , 0.10622119, 0.00158543, 0.11814565, 0.10529208,
        0.04213433]),
 'mean_score_time': array([0.        , 0.32683949, 0.32263837, 0.32266459, 0.        ,
        0.32965264, 0.32067852, 0.32264018, 0.        , 0.32623472,
        0.32395988, 0.31993947, 0.        , 0.32320189, 0.32537103,
        0.31855316]),
 'std_score_time': array([0.        , 0.00314246, 0.00344656, 0.00374388, 0.        ,
        0.00329363, 0.00196706, 0.00337002, 0.        , 0.00186505,
        0.0050223 , 0.00618312, 0.        , 0.00328493, 0.00532715,
        0.00442553]),
 'param_max_features': masked_array(data=[14, 14, 14, 14, 15, 15, 15, 15, 16, 16, 16, 16, 17, 17,
                    17, 17],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_split': masked_array(data=[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_features': 14, 'min_samples_split': 1},
  {'max_features': 14, 'min_samples_split': 2},
  {'max_features': 14, 'min_samples_split': 3},
  {'max_features': 14, 'min_samples_split': 4},
  {'max_features': 15, 'min_samples_split': 1},
  {'max_features': 15, 'min_samples_split': 2},
  {'max_features': 15, 'min_samples_split': 3},
  {'max_features': 15, 'min_samples_split': 4},
  {'max_features': 16, 'min_samples_split': 1},
  {'max_features': 16, 'min_samples_split': 2},
  {'max_features': 16, 'min_samples_split': 3},
  {'max_features': 16, 'min_samples_split': 4},
  {'max_features': 17, 'min_samples_split': 1},
  {'max_features': 17, 'min_samples_split': 2},
  {'max_features': 17, 'min_samples_split': 3},
  {'max_features': 17, 'min_samples_split': 4}],
 'split0_test_score': array([       nan, 0.67380792, 0.67601151, 0.67350187,        nan,
        0.67319581, 0.67435882, 0.67478729,        nan, 0.67356308,
        0.6742364 , 0.67380792,        nan, 0.67319581, 0.67521577,
        0.67288976]),
 'split1_test_score': array([       nan, 0.67643998, 0.67435882, 0.67552182,        nan,
        0.67527698, 0.67588909, 0.6753994 ,        nan, 0.67625635,
        0.6771133 , 0.67233886,        nan, 0.67478729, 0.67325702,
        0.67521577]),
 'split2_test_score': array([       nan, 0.67629775, 0.67715475, 0.67703232,        nan,
        0.67758325, 0.67752204, 0.67715475,        nan, 0.67690989,
        0.67801175, 0.67739961,        nan, 0.67586925, 0.67690989,
        0.67391038]),
 'split3_test_score': array([       nan, 0.67831783, 0.67648139, 0.6790524 ,        nan,
        0.67874633, 0.67739961, 0.68015426,        nan, 0.67960333,
        0.67537953, 0.6777669 ,        nan, 0.6777669 , 0.6790524 ,
        0.67941969]),
 'split4_test_score': array([       nan, 0.6777669 , 0.67813418, 0.67544074,        nan,
        0.67746082, 0.67978697, 0.67788932,        nan, 0.6786239 ,
        0.67892997, 0.67984819,        nan, 0.67807297, 0.67764447,
        0.6794809 ]),
 'mean_test_score': array([       nan, 0.67652607, 0.67642813, 0.67610983,        nan,
        0.67645264, 0.6769913 , 0.67707701,        nan, 0.67699131,
        0.67673419, 0.67623229,        nan, 0.67593844, 0.67641591,
        0.6761833 ]),
 'std_test_score': array([       nan, 0.00156192, 0.00125675, 0.00184957,        nan,
        0.00197711, 0.00181158, 0.00190749,        nan, 0.00208747,
        0.00171298, 0.00275059,        nan, 0.00183038, 0.00200616,
        0.0027676 ]),
 'rank_test_score': array([13,  5,  7, 11, 14,  6,  3,  1, 15,  2,  4,  9, 16, 12,  8, 10])}

In [19]:
clf_m = RandomForestClassifier(n_estimators = 100,max_depth=21,min_samples_leaf=1,max_features=15,min_samples_split=4)
clf_m.fit(X_train, y_train_m)
scores_RF = cross_val_score(clf_m, X_train,y_train_m, cv=5)

In [20]:
scores_RF.mean()

0.6791337556475309

### Testing (Multi-Class Charge Types)

In [21]:
# performing predictions on the test dataset
y_pred_m = clf_m.predict(X_test)

# using metrics module for accuracy calculation
print("ACCURACY OF THE MODEL: ", metrics.accuracy_score(y_test_m, y_pred_m))

ACCURACY OF THE MODEL:  0.6788110278634739

The best result We can get from Random Forest has an accuracy of 0.3788 in test set.
(with meta parameters: n_estimators = 100,max_depth=21,min_samples_leaf=1,max_features=15,min_samples_split=4)